// Practice-question data for AB-900 (Microsoft 365 Copilot).
//
// AB900_QUESTIONS contains REAL exam-prep questions extracted directly from
// the user's authoritative German/English bilingual PDF (Ab-900.pdf). Per
// explicit instruction, only the German content was extracted — no English
// text is present in the final content.
//
// PROGRESS: 101 questions extracted and verified (real-ab900-1 through
// real-ab900-101). The source PDF's own question numbering goes up to 104,
// but a careful count (verified independently three ways: block-splitting,
// counting "Antwort:" answer pages, and a full manual page-by-page listing)
// confirms the PDF contains exactly 101 complete question+answer pairs — the
// printed number 104 does not equal the true count because several numbers
// are reused in the source document for entirely different questions (e.g.
// two distinct questions both printed as "23."), and question 50 was never
// printed as its own page at all. Every answer was verified against the raw
// PDF text; a number of questions with corrupted/incomplete German text in the
// source PDF (missing intro sentences, truncated multi-line statements, or a
// stray formatting quirk breaking automated parsing) were manually
// reconstructed using ONLY text taken directly from elsewhere in this same
// document (its own standard instruction sentences, or hand-transcribing the
// correct raw paragraph) — nothing was invented. See scripts/ab900-extraction/
// for the extraction/parsing/patch scripts used.

import type { PracticeQuestion, PracticeTopic, SingleChoiceQuestion, YesNoQuestion } from "./az900Practice";

export const AB900_TOPICS: PracticeTopic[] = [
  { id: "copilot-grundlagen", title: "Microsoft 365 Copilot Grundlagen", totalQuestions: 32 },
  { id: "copilot-agenten", title: "Copilot-Agenten verwalten", totalQuestions: 9 },
  { id: "sicherheit-identitaet", title: "Sicherheit und Identität", totalQuestions: 20 },
  { id: "purview-compliance", title: "Purview und Compliance", totalQuestions: 27 },
  { id: "verwaltung-governance", title: "Verwaltung und Governance", totalQuestions: 11 },
  { id: "verantwortungsvolle-ki", title: "Verantwortungsvolle KI", totalQuestions: 2 },
];

export const AB900_QUESTIONS: PracticeQuestion[] = [
  {
    type: "yesno",
    id: "real-ab900-1",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein.",
    statements: [
      { text: "Um Microsoft 365 Copilot Chat zu verwenden, um über Webdaten zu argumentieren, benötigen Sie eine Microsoft 365 Copilot-Lizenz", correct: "Nein" },
      { text: "Um den Researcher-Agenten in Microsoft 365 Copilot zu verwenden, benötigen Sie eine Microsoft 365 Copilot-Lizenz", correct: "Ja" },
      { text: "Um einen Agenten in der Microsoft 365 Copilot-App hinzuzufügen, benötigen Sie eine Microsoft 365 Copilot-Lizenz", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-2",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein.",
    statements: [
      { text: "Microsoft 365 Copilot zeigt nur die organisatorischen Daten an, für die einzelne Benutzer Berechtigungen haben", correct: "Ja" },
      { text: "Microsoft 365 Copilot verwendet dieselben zugrunde liegenden Kontrollen für den Datenzugriff wie andere Microsoft 365-Dienste", correct: "Ja" },
      { text: "Microsoft 365 Copilot kann Konnektoren verwenden, um Informationen aus Datenquellen von Drittanbietern abzurufen", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-3",
    topicId: "copilot-grundlagen",
    prompt: "In Microsoft 365 Copilot sollten Sie verwenden ___ mehrstufiges Schlussfolgern über unstrukturierte Daten durchführen.",
    options: [
      { id: "A", text: "ein Notebook" },
      { id: "B", text: "Chat" },
      { id: "C", text: "der Analyst-Agent" },
      { id: "D", text: "der Forscher-Agent" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-4",
    topicId: "copilot-agenten",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365 E5-Abonnement. Sie müssen sicherstellen, dass ein Cloud-Dienst eines Drittanbieters sich bei Microsoft Entra authentifizieren kann. Was sollten Sie konfigurieren?",
    options: [
      { id: "A", text: "Ein Microsoft 365 Copilot-Connector" },
      { id: "B", text: "Mehrstufige Authentifizierung (MFA)" },
      { id: "C", text: "Eine Richtlinie für bedingten Zugriff" },
      { id: "D", text: "Eine App-Registrierung" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-5",
    topicId: "verantwortungsvolle-ki",
    prompt: "Das Microsoft-Prinzip für verantwortungsbewusste KI in Bezug auf ___ erfordert die Überwachung von KI-Systemen, um sicherzustellen, dass Menschen die Kontrolle behalten.",
    options: [
      { id: "A", text: "Rechenschaftspflicht" },
      { id: "B", text: "Inklusivität" },
      { id: "C", text: "Datenschutz und Sicherheit" },
      { id: "D", text: "Zuverlässigkeit & Sicherheit" },
      { id: "E", text: "Transparenz" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-6",
    topicId: "copilot-grundlagen",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen die Identity Secure Score Ihrer Organisation bewerten. Welche zwei Faktoren beeinflussen die Punktzahl? (Jede richtige Antwort stellt die vollständige Lösung dar. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Die Berechtigungen der SharePoint-Site" },
      { id: "B", text: "Die Anzahl der globalen Administratoren" },
      { id: "C", text: "Passwörter, die niemals ablaufen" },
      { id: "D", text: "Der Standort der Benutzer" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-7",
    topicId: "sicherheit-identitaet",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen die Auswirkungen eines kürzlich auf E-Mail-Benutzer abzielenden Phishing- Vorfalls überprüfen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das Microsoft Defender-Portal" },
      { id: "B", text: "Das Microsoft 365 Admin Center" },
      { id: "C", text: "Das Microsoft Entra Admin Center" },
      { id: "D", text: "Das Microsoft Exchange Admin Center" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-8",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen einem Benutzer eine Lizenz zuweisen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das Microsoft Purview-Portal" },
      { id: "B", text: "Das Microsoft 365 Admin Center" },
      { id: "C", text: "Das Microsoft Teams Admin Center" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-9",
    topicId: "copilot-grundlagen",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Microsoft 365 Copilot ruft Daten von Azure OpenAI mithilfe von Microsoft Graph ab." },
      { id: "B", text: "Microsoft 365 Copilot ruft Daten von externen Benutzern mithilfe von Microsoft Graph ab." },
      { id: "C", text: "Microsoft 365 Copilot ruft Daten von Microsoft SharePoint-Dateien mithilfe von Microsoft Graph ab." },
      { id: "D", text: "Microsoft 365 Copilot ruft Daten von Internetsuchmaschinen mithilfe von Microsoft Graph ab." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-10",
    topicId: "sicherheit-identitaet",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Microsoft Entra Privileged Identity Management (PIM) bietet eingeschränkten Zugriff auf Microsoft 365-Dienste." },
      { id: "B", text: "Microsoft Entra Privileged Identity Management (PIM) bietet die Verwaltung des Benutzerlebenszyklus." },
      { id: "C", text: "Microsoft Entra Privileged Identity Management (PIM) bietet die Verwaltung von Unternehmensanwendungen." },
      { id: "D", text: "Microsoft Entra Privileged Identity Management (PIM) bietet zeitlich begrenzte Rollenzuweisung." },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-11",
    topicId: "sicherheit-identitaet",
    prompt: "Ein Benutzer namens User5 navigiert zu https://myapps.microsoft.com. Nachdem er seinen Benutzernamen und sein Passwort eingegeben hat, erhält User5 die folgende Nachricht auf seinem Mobilgerät. Verwenden Sie die Dropdown-Menüs, um die Antwort auszuwählen, die die Aussage basierend auf den im Diagramm dargestellten Informationen vervollständigt.",
    options: [
      { id: "A", text: "User5 verwendet E-Mail-OTP für die Multi-Faktor-Authentifizierung (MFA)." },
      { id: "B", text: "User5 verwendet die Microsoft Authenticator-App für die Multi-Faktor- Authentifizierung (MFA)." },
      { id: "C", text: "User5 verwendet SMS für die Multi-Faktor-Authentifizierung (MFA)." },
      { id: "D", text: "User5 verwendet ein Temporäres Zugangspasswort für die Multi-Faktor- Authentifizierung (MFA)." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-12",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Microsoft Defender für Office 365 bietet Schutz vor Phishing- und Malware-Angriffen", correct: "Ja" },
      { text: "Microsoft Defender für Identität überwacht Identitäten in Active-Directory-Domänen", correct: "Ja" },
      { text: "Microsoft Defender Schwachstellenmanagement bietet Schutz für Software-as-a-Service-(SaaS)-Anwendungen", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-13",
    topicId: "copilot-grundlagen",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement, das eine Microsoft SharePoint-Website namens Site1 enthält. Die Berechtigungen für Site1 sind wie in der folgenden Abbildung dargestellt konfiguriert. Sie erstellen einen neuen Benutzer namens User1 im Abonnement. Verwenden Sie die Dropdown-Menüs, um die Antwort auszuwählen, die die Aussage basierend auf den im Diagramm dargestellten Informationen vervollständigt.",
    options: [
      { id: "A", text: "User1 ist ein Besucher der Site1." },
      { id: "B", text: "User1 ist ein Eigentümer der Site1." },
      { id: "C", text: "User1 ist ein Mitglied der Site1." },
      { id: "D", text: "User1 ist daran gehindert, auf Site1 zuzugreifen." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-14",
    topicId: "verwaltung-governance",
    prompt: "Ein multinationales Unternehmen mit über 5.000 Benutzern führt Microsoft 365 Copilot ein. Das Unternehmen verfügt derzeit über eine Mischung aus Microsoft 365 E3- und Office 365 E3-Lizenzen für seine Informationsmitarbeiter. Der IT-Administrator muss sicherstellen, dass alle Benutzer auf die vollständigen generativen KI-Funktionen von Copilot in Anwendungen wie Word und Excel zugreifen können. Welche minimale Lizenzmaßnahme ist erforderlich, um allen bestehenden Informationsmitarbeitern den Zugriff auf Microsoft 365 Copilot zu ermöglichen?",
    options: [
      { id: "A", text: "Alle vorhandenen Office 365 E3-Lizenzen auf Microsoft 365 E5-Lizenzen upgraden." },
      { id: "B", text: "Die separate Microsoft 365 Copilot-Zusatzlizenz für alle Benutzer erwerben." },
      { id: "C", text: "Alle bestehenden Lizenzen von Enterprise-Plänen auf Microsoft 365 Business Premium-Pläne umstellen." },
      { id: "D", text: "Nur die Microsoft 365 Copilot-Zusatzlizenz für Benutzer mit Microsoft 365 E3-Lizenzen erwerben, da Office 365 E3 nicht berechtigt ist." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-15",
    topicId: "copilot-grundlagen",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Wenn ein Benutzer einen Microsoft 365 Copilot-Agenten teilt, können Sie Microsoft Foundry verwenden, um Benutzer daran zu hindern, den Agenten zu verwenden." },
      { id: "B", text: "Wenn ein Benutzer einen Microsoft 365 Copilot-Agenten teilt, können Sie Microsoft Copilot Studio verwenden, um Benutzer daran zu hindern, den Agenten zu verwenden." },
      { id: "C", text: "Wenn ein Benutzer einen Microsoft 365 Copilot-Agenten teilt, können Sie das Microsoft 365 Admin Center verwenden, um Benutzer daran zu hindern, den Agenten zu verwenden." },
      { id: "D", text: "Wenn ein Benutzer einen Microsoft 365 Copilot-Agenten teilt, können Sie das Power Apps-Portal verwenden, um Benutzer daran zu hindern, den Agenten zu verwenden." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-16",
    topicId: "verwaltung-governance",
    prompt: "Das IT-Administrationsteam Ihrer Organisation, Contoso Ltd., hat einen neuen Domainnamen, contosoglobal.com, erworben und muss ihn in ihrer Microsoft 365-Umgebung hinzufügen. Diese neue Domain wird für alle neuen Benutzerprinzipalnamen (UPNs) und E-Mail-Adressen verwendet. Welchen Abschnitt des Microsoft 365-Administrationscenters muss der Administrator verwenden, um die neue Domain zu verwalten, zu verifizieren und als Standard für neue Benutzer einzustellen?",
    options: [
      { id: "A", text: "Einstellungen > Organisations-Einstellungen > Dienste" },
      { id: "B", text: "Abrechnung > Lizenzen > Produktliste" },
      { id: "C", text: "Einrichtung > Domäneneinrichtung > Domäne verbinden" },
      { id: "D", text: "Einstellungen > Domains" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-17",
    topicId: "sicherheit-identitaet",
    prompt: "Ein Finanzbenutzer erhielt eine ausgeklügelte Phishing-E-Mail mit einem schädlichen Link, der neutralisiert wurde. Das Sicherheitsteam benötigt eine einzige, zentrale Ansicht, um den Vorfallzeitplan, verwandte Warnungen (E-Mail und Endpunkt) und empfohlene Maßnahmen zur Stärkung der Sicherheitsposition für E-Mail und Endpunkte zu überprüfen. Welche Defender XDR-Funktion oder welcher Portalbereich bietet dem Sicherheitsteam diese einheitliche Vorfallchronik und Verbesserungsempfehlungen?",
    options: [
      { id: "A", text: "Microsoft Defender for Identity" },
      { id: "B", text: "Microsoft Defender for Office 365" },
      { id: "C", text: "Microsoft Defender Vulnerability Management" },
      { id: "D", text: "Die einheitliche Erlebniswelt für Vorfälle und Warnungen sowie Secure Score im Microsoft Defender-Portal" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-18",
    topicId: "sicherheit-identitaet",
    prompt: "Ein Benutzer ist daran gehindert, sich anzumelden, und der Administrator vermutet Conditional Access oder eine Risikosigniererkennung. Welche zwei Tools im Microsoft Entra Admin Center sollte der Administrator zuerst verwenden, um den genauen Anmeldefehler und die dafür verantwortliche Richtlinie zu identifizieren? (Jede richtige Auswahl stellt einen Teil der Lösung dar. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Conditional Access What If Tool" },
      { id: "B", text: "Microsoft 365 Service Health Dashboard" },
      { id: "C", text: "Anmeldeprotokolle und Fehlerbehebung und Support in Microsoft Entra ID" },
      { id: "D", text: "Exchange Online Nachrichtenverfolgung" },
      { id: "E", text: "Microsoft Entra ID Anwendungsproxy" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-19",
    topicId: "purview-compliance",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Microsoft Purview Compliance Manager bietet eine risikobasierte Compliance-Bewertung, um Ihnen zu helfen, Ihre Compliance-Situation zu verstehen", correct: "Ja" },
      { text: "Microsoft Purview Compliance Manager bietet Schritt-für-Schritt-Anleitungen zur Behebung von Compliance-Problemen", correct: "Ja" },
      { text: "Compliance Manager ist Teil von Microsoft Defender", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-20",
    topicId: "copilot-agenten",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie stellen fest, dass Microsoft SharePoint-Dateien mit Benutzern außerhalb Ihrer Organisation geteilt werden. Sie müssen herausfinden, welche Dateien mit den externen Benutzern geteilt werden. Welchen Bericht sollten Sie im SharePoint Admin Center verwenden? (Wählen Sie zur Beantwortung den entsprechenden Bericht im Antwortbereich aus.)",
    options: [
      { id: "A", text: "Agenten-Einblicke" },
      { id: "B", text: "App-Einblicke" },
      { id: "C", text: "Änderungsverlauf" },
      { id: "D", text: "Datenzugriffsverwaltung" },
      { id: "E", text: "OneDrive-Konten" },
      { id: "F", text: "Vergleich von Website-Richtlinien" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-21",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation hat ein Microsoft 365-Abonnement. Die Personalabteilung Ihres Unternehmens bittet um eine Kopie aller kürzlich von einem Benutzer namens User1 geänderten Dateien. Was sollten Sie im Microsoft Purview-Portal verwenden? (Wählen Sie zur Beantwortung die entsprechenden Lösungen im Antwortbereich aus.)",
    options: [
      { id: "A", text: "Überprüfung" },
      { id: "B", text: "Datenkatalog" },
      { id: "C", text: "Verlustprävention von Daten" },
      { id: "D", text: "eDiscovery" },
      { id: "E", text: "Informationsschutz" },
      { id: "F", text: "Insider-Risikomanagement" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-22",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen Microsoft Purview verwenden, um die folgenden Anforderungen zu erfüllen: • Verhindern, dass Benutzer Dateien teilen, die persönlich identifizierbare Informationen (PII) enthalten. • Maschinelles Lernen verwenden, um ein Modell zu trainieren, das sensible Inhalte erkennt. Welche Microsoft Purview- Lösung sollten Sie für jede Anforderung verwenden? (Um zu antworten, wählen Sie die entsprechenden Optionen im Antwortbereich aus. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Verhindern, dass Benutzer PII teilen: Kommunikations-Compliance Maschinelles Lernen verwenden, um ein Modell zu trainieren: Datenschutzverletzungsvermeidung" },
      { id: "B", text: "Verhindern, dass Benutzer PII teilen: Datenschutzverletzungsvermeidung Maschinelles Lernen verwenden, um ein Modell zu trainieren: Informationsschutz" },
      { id: "C", text: "Verhindern, dass Benutzer PII teilen: Informationsschutz Maschinelles Lernen verwenden, um ein Modell zu trainieren: Insider-Risikomanagement" },
      { id: "D", text: "Verhindern, dass Benutzer PII teilen: Insider-Risikomanagement Maschinelles Lernen verwenden, um ein Modell zu trainieren: Kommunikations-Compliance" },
      { id: "E", text: "Verhindern, dass Benutzer PII teilen: Datenschutzverletzungsvermeidung Maschinelles Lernen verwenden, um ein Modell zu trainieren: DSPM für KI" },
      { id: "F", text: "Verhindern, dass Benutzer PII teilen: DSPM für KI Maschinelles Lernen verwenden, um ein Modell zu trainieren: Insider-Risikomanagement" },
    ],
    correct: "E",
    explanation: "",
  },
  {
    id: "real-ab900-23",
    topicId: "purview-compliance",
    prompt: "Sie möchten die von einem Serviceadministrator in Microsoft 365 durchgeführten administrativen Maßnahmen anzeigen. Wählen Sie für jede der folgenden Aussagen „Ja“, wenn die Aussage zutrifft. Andernfalls wählen Sie „Nein“. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Sie können Suche & Intelligenz im Microsoft 365 Admin Center verwenden: Ja Sie können Überwachung im Microsoft Defender-Portal verwenden: Ja Sie können Überwachung im Microsoft Purview-Portal verwenden: Ja" },
      { id: "B", text: "Sie können Suche & Intelligenz im Microsoft 365 Admin Center verwenden: Ja Sie können Überwachung im Microsoft Defender-Portal verwenden: Ja Sie können Überwachung im Microsoft Purview-Portal verwenden: Nein" },
      { id: "C", text: "Sie können Suche & Intelligenz im Microsoft 365 Admin Center verwenden: Ja Sie können Überwachung im Microsoft Defender-Portal verwenden: Nein Sie können Überwachung im Microsoft Purview-Portal verwenden: Ja" },
      { id: "D", text: "Sie können Suche & Intelligenz im Microsoft 365 Admin Center verwenden: Nein Sie können Überwachung im Microsoft Defender-Portal verwenden: Ja Sie können Überwachung im Microsoft Purview-Portal verwenden: Nein" },
      { id: "E", text: "Sie können Suche & Intelligenz im Microsoft 365 Admin Center verwenden: Nein Sie können Überwachung im Microsoft Defender-Portal verwenden: Nein Sie können Überwachung im Microsoft Purview-Portal verwenden: Ja" },
      { id: "F", text: "Sie können Suche & Intelligenz im Microsoft 365 Admin Center verwenden: Nein Sie können Audit im Microsoft Defender-Portal verwenden: Nein Sie können Audit im Microsoft Purview-Portal verwenden: Nein" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-24",
    topicId: "sicherheit-identitaet",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Conditional Access-Richtlinien werden über das Microsoft Defender-Portal konfiguriert." },
      { id: "B", text: "Conditional Access-Richtlinien werden nur auf lokale Ressourcen angewendet." },
      { id: "C", text: "Conditional Access-Richtlinien bieten Kontrolle darüber, wie Benutzer auf Cloud-Apps zugreifen können." },
      { id: "D", text: "Conditional Access-Richtlinien erfordern ein Microsoft Exchange-Postfach." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-25",
    topicId: "sicherheit-identitaet",
    prompt: "Ein Administrator muss den Zugriff auf eine SharePoint-Website für eine sensible HR- Site verwalten und Copilot-Add-on-Lizenzen den 50 Mitgliedern des Teams \"HR-Data- Users\" zuweisen. Die Mitgliedschaft ändert sich aufgrund der hohen Fluktuation häufig. Welches Microsoft Entra-Objekt ist sowohl für die Zugriffskontrolle als auch für die lizenzbasierte Gruppenverwaltung die effizienteste Wahl?",
    options: [
      { id: "A", text: "Dynamische Sicherheitsgruppe" },
      { id: "B", text: "E-Mail-fähige Sicherheitsgruppe" },
      { id: "C", text: "Microsoft 365-Gruppe" },
      { id: "D", text: "Verteilerliste" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-26",
    topicId: "purview-compliance",
    prompt: "Sie verwenden Microsoft 365 Copilot. Womit erstellt Copilot Antworten basierend auf in Microsoft SharePoint gespeicherten Unternehmensdaten?",
    options: [
      { id: "A", text: "Microsoft Intune" },
      { id: "B", text: "Microsoft Defender" },
      { id: "C", text: "Microsoft Graph" },
      { id: "D", text: "Microsoft Purview" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-27",
    topicId: "purview-compliance",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Sie können die Data Lifecycle Management Microsoft Purview-Lösung verwenden, um Microsoft 365 Copilot-Eingaben zu erkennen, die sensible Informationen enthalten." },
      { id: "B", text: "Sie können die DSPM for AI Microsoft Purview-Lösung verwenden, um Microsoft 365 Copilot-Eingaben zu erkennen, die sensible Informationen enthalten." },
      { id: "C", text: "Sie können die Information Barriers Microsoft Purview-Lösung verwenden, um Microsoft 365 Copilot-Eingaben zu erkennen, die sensible Informationen enthalten." },
      { id: "D", text: "Sie können die Information Protection Microsoft Purview-Lösung verwenden, um Microsoft 365 Copilot-Eingaben zu erkennen, die sensible Informationen enthalten." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-28",
    topicId: "purview-compliance",
    prompt: "Ein Marketing-Benutzer bittet Copilot, den „neueste Haushaltsvorschlag“ zusammenzufassen, der auf einer SharePoint-Website gespeichert ist, die nur für die Finanzabteilung zugänglich ist. Der Marketing-Benutzer ist kein Mitglied der Website. Welches Prinzip steuert das Verhalten von Copilot und verhindert, dass es die eingeschränkten Inhalte zurückgibt?",
    options: [
      { id: "A", text: "Copilot wendet vor der Verarbeitung der Anfrage die Zero-Trust-Verifizierung an." },
      { id: "B", text: "Copilot verwendet nur Inhalte, die ausdrücklich mit einem bestimmten Sensitivitätslabel gekennzeichnet sind." },
      { id: "C", text: "Copilot setzt strikt die bestehenden Microsoft 365-Berechtigungen des Benutzers durch und gibt keine Inhalte zurück, auf die der Benutzer keinen Zugriff hat." },
      { id: "D", text: "Microsoft Purview DLP schwärzt automatisch finanzielle Zahlen in Copilot- Antworten." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-29",
    topicId: "copilot-grundlagen",
    prompt: "Wenn ein Benutzer Copilot fragt: „Welche aktuellen Dokumente wurden mir zu 'Projekt Phoenix' geteilt?“, liefert Copilot personalisierte Dokumente aus OneDrive, SharePoint und Teams. Welche Hauptrolle spielt Microsoft Graph bei der Ermöglichung dieser Antwort?",
    options: [
      { id: "A", text: "Es stellt dem LLM sein vortrainiertes Weltwissen zur Verfügung." },
      { id: "B", text: "Es dient als Engine zur Einhaltung von Redaktionsrichtlinien." },
      { id: "C", text: "Es fungiert als semantischer Index, der die Anfrage des Benutzers auf den Kontext, die Beziehungen und Berechtigungen des Benutzers für organisatorische Daten abbildet." },
      { id: "D", text: "Es setzt Conditional Access-Richtlinien in Echtzeit durch." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-30",
    topicId: "verwaltung-governance",
    prompt: "Für jede der folgenden Aussagen wählen Sie 'Ja', wenn die Aussage zutrifft. Andernfalls wählen Sie 'Nein'. (HINWEIS: Jede korrekte Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Damit Administratoren SharePoint Advanced Management verwenden können, benötigen alle Benutzer in Ihrer Organisation eine Microsoft 365 Copilot-Lizenz", correct: "Nein" },
      { text: "SharePoint Advanced Management kann helfen, den Zugriff von Microsoft 365 Copilot auf Microsoft SharePoint-Inhalte einzuschränken", correct: "Ja" },
      { text: "SharePoint Advanced Management ist als eigenständige Lizenz für Organisationen ohne Microsoft 365 Copilot verfügbar", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-31",
    topicId: "verantwortungsvolle-ki",
    prompt: "Ein KI-Agent, der darauf vorbereitet wird, Kundenprotokolle zusammenzufassen, zeigt eine Voreingenommenheit zugunsten bestimmter geografischer Regionen. Welches Microsoft Responsible AI-Prinzip wird in erster Linie verletzt und sollte vor der Bereitstellung angesprochen werden?",
    options: [
      { id: "A", text: "Fairness" },
      { id: "B", text: "Transparenz" },
      { id: "C", text: "Verantwortlichkeit" },
      { id: "D", text: "Inklusivität" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-32",
    topicId: "sicherheit-identitaet",
    prompt: "Compliance benötigt einen Bericht, der SharePoint-Websites auflistet, die hochsensible Dokumente enthalten, aber mit großen Gruppen wie „Jeder außer externen Benutzern\" geteilt werden. Welche Microsoft-Funktion ist dafür ausgelegt, Data Access Governance (DAG)-Berichte zu erstellen, die sensible Inhalte sowie eine nachsichtigere Freigabepraxis identifizieren?",
    options: [
      { id: "A", text: "Microsoft Entra ID Protection" },
      { id: "B", text: "Microsoft Purview Data Loss Prevention (DLP)" },
      { id: "C", text: "Microsoft Defender for Cloud Apps" },
      { id: "D", text: "SharePoint Advanced Management (SAM)" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-33",
    topicId: "purview-compliance",
    prompt: "Sie haben eine Microsoft SharePoint-Website wie in der folgenden Abbildung gezeigt. Sie müssen die Einstellungen von SLabel1 anzeigen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das Microsoft Defender-Portal" },
      { id: "B", text: "Das SharePoint-Admin-Center" },
      { id: "C", text: "Das Microsoft 365-Admin-Center" },
      { id: "D", text: "Das Microsoft Purview-Portal" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-34",
    topicId: "purview-compliance",
    prompt: "Wählen Sie die Antwort, die den Satz richtig vervollständigt.",
    options: [
      { id: "A", text: "Sie können Microsoft Defender für Office 365 verwenden, um Bedrohungsindikatoren zu überprüfen, die über E-Mail-, Identitäts- und Gerätevorfälle hinweg in einer einzigen Ansicht korreliert sind." },
      { id: "B", text: "Sie können Microsoft Defender XDR verwenden, um Bedrohungsindikatoren zu überprüfen, die über E-Mail-, Identitäts- und Gerätevorfälle hinweg in einer einzigen Ansicht korreliert sind." },
      { id: "C", text: "Sie können Microsoft Purview Compliance Manager verwenden, um Bedrohungsindikatoren zu überprüfen, die über E-Mail-, Identitäts- und Gerätevorfälle hinweg in einer einzigen Ansicht korreliert sind." },
      { id: "D", text: "Sie können Microsoft Purview Data Loss Prevention verwenden, um Bedrohungsindikatoren zu überprüfen, die über E-Mail-, Identitäts- und Gerätevorfälle hinweg in einer einzigen Ansicht korreliert sind." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-35",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement, das einen Benutzer namens User1 enthält. User1 plant, Ihr Unternehmen in zwei Wochen zu verlassen. Sie müssen die Aktivitäten von User1 erfassen, um festzustellen, ob der Benutzer Daten exfiltriert. Welche Microsoft Purview-Lösung sollten Sie verwenden?",
    options: [
      { id: "A", text: "Kommunikations-Compliance" },
      { id: "B", text: "Verwaltung der Datensicherheitslage" },
      { id: "C", text: "Verwaltung von Insider-Risiken" },
      { id: "D", text: "Datenlebenszyklusverwaltung" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-36",
    topicId: "verwaltung-governance",
    prompt: "Ihre Organisation hat ein Microsoft 365-Abonnement, das Microsoft SharePoint- Websites und Microsoft Teams-Teams enthält. Sie stellen fest, dass die Websites und Teams mit Benutzern außerhalb Ihrer Organisation geteilt werden. Sie müssen herausfinden, welche Websites und Teams mit den externen Benutzern geteilt wurden. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das SharePoint-Admincenter" },
      { id: "B", text: "Das Microsoft Teams-Admincenter" },
      { id: "C", text: "Das Microsoft 365-Admincenter" },
      { id: "D", text: "Das Microsoft Defender-Portal" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-37",
    topicId: "copilot-grundlagen",
    prompt: "Eine Organisation verlangt, dass Copilot niemals Ergebnisse aus öffentlichen Websuchen in Antworten einbezieht, um eine mögliche Offenlegung interner Aufforderungen/Daten zu vermeiden. Welche Copilot-Funktion sollte ein Administrator deaktivieren, um die Webgrundlage für Copilot-Antworten zu blockieren?",
    options: [
      { id: "A", text: "Copilot in Word" },
      { id: "B", text: "Copilot für Microsoft 365" },
      { id: "C", text: "Copilot Chat" },
      { id: "D", text: "Copilot-Funktionen in Microsoft 365 Apps" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-38",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Der Microsoft 365 Copilot-Nutzungsbericht kann verwendet werden, um von Benutzern eingereichte Copilot-Prompts anzuzeigen", correct: "Nein" },
      { text: "Der Microsoft 365 Copilot-Nutzungsbericht zeigt die Gesamtzahl der eindeutigen Benutzer in Ihrer Organisation", correct: "Ja" },
      { text: "Der Microsoft 365 Copilot-Nutzungsbericht zeigt die Copilot-Nutzung jeder einzelnen Microsoft 365-App", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-39",
    topicId: "copilot-grundlagen",
    prompt: "Sie planen, einen Agenten in der Microsoft 365 Copilot-App zu erstellen, um ein geschäftliches Problem zu lösen. Was sind zwei Gründe, den Agenten zu erstellen? (Jede richtige Antwort stellt eine vollständige Lösung dar. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Sie müssen ein benutzerdefiniertes KI-Modell verwenden." },
      { id: "B", text: "Sie müssen eine benutzerdefinierte Anweisungsmenge verwenden, die sich von der der Chat-Erfahrung unterscheidet." },
      { id: "C", text: "Sie müssen über eine bestimmte Website nachdenken." },
      { id: "D", text: "Sie müssen verwandte Chats in einem Copilot-Notizbuch gruppieren." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-40",
    topicId: "purview-compliance",
    prompt: "Ein wesentliches Governance-Risiko bei der Implementierung von Microsoft 365 Copilot ist das mögliche Übermitteln von Unternehmensdaten. Der Chief Compliance Officer ist besorgt, dass ein Benutzer, da Copilot alle Daten nutzt, auf die er Zugriff hat, versehentlich Zugang zu sensiblen Informationen erhalten könnte, auf die er eigentlich keinen Zugriff haben sollte. Was ist die häufigste Ursache dieses Risikos des übermäßigen Teilens, die Administratoren als Governance-Aufgabe mit hoher Priorität angehen müssen, bevor Copilot breit eingesetzt wird?",
    options: [
      { id: "A", text: "Copilot umgeht SharePoint-Zugriffskontrollen, wenn Inhalte indexiert werden." },
      { id: "B", text: "Zu weit gefasste Berechtigungen für Sites oder Dateien." },
      { id: "C", text: "Die Chatprotokolle von Copilot unterliegen nicht der eDiscovery oder Aufbewahrung." },
      { id: "D", text: "Das Training des Azure OpenAI-Modells verwendet Mandantendaten und behält sie im Mandanten." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-41",
    topicId: "sicherheit-identitaet",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen Sicherheitsvorfälle und Warnungen untersuchen, die von den Windows 11- Geräten in Ihrer Organisation ausgelöst wurden. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Microsoft Entra ID Protection" },
      { id: "B", text: "Microsoft Defender for Identity" },
      { id: "C", text: "Microsoft Purview Insider Risk Management" },
      { id: "D", text: "Microsoft Defender for Endpoint" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-42",
    topicId: "verwaltung-governance",
    prompt: "Ihr Unternehmen verlangt, dass alle Microsoft SharePoint-Websites mindestens zwei Besitzer haben. Sie müssen sicherstellen, dass Websites, die weniger als zwei Besitzer haben, als nur lesbar markiert werden, wenn die Websites NICHT behoben werden. Was sollten Sie im SharePoint-Admincenter konfigurieren?",
    options: [
      { id: "A", text: "Einschränkung des Zugriffs auf Website-Ebene" },
      { id: "B", text: "Berichte zur Datenzugriffsverwaltung" },
      { id: "C", text: "Website-Lebenszyklusverwaltung" },
      { id: "D", text: "Richtlinie zum Blockieren von Downloads für SharePoint und OneDrive" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-43",
    topicId: "copilot-grundlagen",
    prompt: "Der IT-Leiter möchte aggregierte, mandantenbezogene Kennzahlen wie aktive Copilot-Benutzer, Nutzung nach App und Prompt-Kategorien, um den ROI von Copilot zu messen. Welches Verwaltungstool bietet diese aggregierte Adoption- und Nutzungsauswertung?",
    options: [
      { id: "A", text: "Microsoft Purview Auditprotokoll" },
      { id: "B", text: "Copilot-Analyse-Dashboard" },
      { id: "C", text: "Microsoft Entra ID Anmeldeprotokolle" },
      { id: "D", text: "Microsoft 365 Service-Status" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-44",
    topicId: "copilot-grundlagen",
    prompt: "Bevor ein in Copilot Studio erstellter KI-Agent, der eine Verbindung zu einer lokalen Finanzdatenbank herstellt, veröffentlicht werden kann, muss ein Administrator den Zugriff, die Leistung und den Lebenszyklusstatus überprüfen. Welche zwei Microsoft-Admin-Center werden hauptsächlich verwendet, um den Lebenszyklus und die Umgebungseinstellungen des Agenten zu verwalten und zu überwachen? (Jede richtige Auswahl stellt einen Teil der Lösung dar. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Microsoft Purview-Portal" },
      { id: "B", text: "Microsoft Entra-Admincenter" },
      { id: "C", text: "Microsoft 365-Admincenter" },
      { id: "D", text: "Microsoft Power Platform-Admin" },
      { id: "E", text: "Exchange-Administrationscenter" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-45",
    topicId: "verwaltung-governance",
    prompt: "Wählen Sie die Antwort, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Vom SharePoint-Admincenter aus können Sie einen Server erstellen." },
      { id: "B", text: "Vom SharePoint-Admincenter aus können Sie einen Benutzer erstellen." },
      { id: "C", text: "Vom SharePoint-Admincenter aus können Sie eine Website erstellen." },
      { id: "D", text: "Vom SharePoint-Admincenter aus können Sie eine Rolle erstellen." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-46",
    topicId: "copilot-agenten",
    prompt: "Sie müssen einen Microsoft 365 Copilot-Agenten erstellen, der Diagramme und Visualisierungen basierend auf einer Microsoft Excel-Arbeitsmappe erstellen kann. Was sollten Sie für den Agenten konfigurieren?",
    options: [
      { id: "A", text: "Die Bildgenerierungsfunktion" },
      { id: "B", text: "Die Scrum Assistant-Vorlage" },
      { id: "C", text: "Die Customer Insights Assistant-Vorlage" },
      { id: "D", text: "Die Code-Interpreter-Funktion" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-47",
    topicId: "verwaltung-governance",
    prompt: "Ihr Unternehmen testet die Verwendung von Microsoft 365 Copilot und hat 100 Microsoft 365 Copilot-Lizenzen erworben. Sie müssen detaillierte Berichte über die Nutzung von Copilot in Microsoft Teams anzeigen, wie z. B. zusammengefasste Besprechungsstunden durch Copilot und durch Copilot vorgenommene Besprechungsaktionen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Der Microsoft 365 Copilot-Bereitschaftsbericht im Microsoft 365 Admin Center" },
      { id: "B", text: "Der Microsoft 365 Copilot-Nutzungsbericht im Microsoft 365 Admin Center" },
      { id: "C", text: "Das Microsoft 365 Copilot-Dashboard in Microsoft Viva Insights" },
      { id: "D", text: "Der Microsoft 365 Apps-Nutzungsbericht im Microsoft 365 Admin Center" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-48",
    topicId: "copilot-agenten",
    prompt: "Ein Benutzer namens User1 erstellt einen Microsoft 365 Copilot-Agenten namens Agent1 und teilt den Agenten mit einem Benutzer namens User2. Was passiert, wenn ein Administrator Agent1 blockiert?",
    options: [
      { id: "A", text: "Agent1 ist für User1 und User2 zugänglich, bis die Benutzer den Agenten manuell deinstallieren. Kein anderer Benutzer kann Agent1 installieren." },
      { id: "B", text: "Agent1 ist für User1 und User2 zugänglich, und kein anderer Benutzer kann Agent1 installieren." },
      { id: "C", text: "Agent1 wird von User2 entfernt, und User1 kann weiterhin Agent1 verwenden." },
      { id: "D", text: "Agent1 wird von User1 und User2 entfernt, und kein Benutzer kann Agent1 installieren." },
    ],
    correct: "D",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-49",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Administratoren können einen bestimmten Copilot-Agenten von allen Benutzern entfernen", correct: "Ja" },
      { text: "Vom Microsoft 365 Admin Center aus können Administratoren die Eingabeaufforderungen eines Copilot-Agenten konfigurieren", correct: "Nein" },
      { text: "Administratoren können Copilot-Agenten bestimmten Benutzern bereitstellen", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-50",
    topicId: "verwaltung-governance",
    prompt: "Wählen Sie die Antwort, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Vom Microsoft Teams Admin Center aus können Sie einem Benutzer eine Teams-Lizenz zuweisen." },
      { id: "B", text: "Vom Microsoft Teams Admin Center aus können Sie den Teams-Client bereitstellen." },
      { id: "C", text: "Vom Microsoft Teams Admin Center aus können Sie ein Teams-Raumgerät verwalten." },
      { id: "D", text: "Vom Microsoft Teams Admin Center aus können Sie verhindern, dass Benutzer Teams erstellen." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-51",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Alle Benutzer haben Lizenzen für Microsoft 365 Copilot. Sie müssen ermitteln, wo sensible Inhalte während der Copilot-Interaktionen verwendet werden, die Nutzungsmuster der Inhalte analysieren und Empfehlungen zur Anwendung der geeigneten Schutzmaßnahmen geben. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Microsoft Viva Insights" },
      { id: "B", text: "Die Microsoft Purview DSPM für AI-Lösung" },
      { id: "C", text: "Microsoft Security Copilot" },
      { id: "D", text: "Die Microsoft Purview Insider Risk Management-Lösung" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-52",
    topicId: "copilot-agenten",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Allen Benutzern wurden Microsoft 365 Copilot-Lizenzen zugewiesen. Einige Benutzer berichten, dass sie Copilot-Antworten erhalten, die Informationen von einer Microsoft SharePoint-Website namens Finance enthalten. Die Benutzer geben an, dass die Informationen geschäftlich sensibel sind. Sie müssen verhindern, dass Copilot Antworten bereitstellt, die Informationen von der Finance-Website enthalten. Was sollten Sie tun?",
    options: [
      { id: "A", text: "Erstellen Sie eine Informationsbarriere (IB)-Richtlinie in Microsoft Purview." },
      { id: "B", text: "Erstellen Sie einen Datenconnector in Microsoft Defender." },
      { id: "C", text: "Erstellen Sie eine Richtlinie für bedingten Zugriff in Microsoft Entra." },
      { id: "D", text: "Konfigurieren Sie die Berechtigungen auf der Finance-Website." },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-53",
    topicId: "copilot-grundlagen",
    prompt: "Ein Manager fragt: „Was ist der hauptsächliche Unterschied in den Fähigkeiten zwischen Microsoft 365 Copilot, das in Word/Excel integriert ist, und einem benutzerdefinierten KI-Agenten, der in Copilot Studio erstellt wurde?“ Was ist die richtige Antwort?",
    options: [
      { id: "A", text: "Nur der integrierte Copilot kann auf Microsoft Graph-Daten zugreifen und diese zusammenfassen." },
      { id: "B", text: "Der integrierte Copilot ist ein allgemeiner Produktivitätsassistent. Benutzerdefinierte KI-Agenten sind für spezifische mehrstufige Aufgaben und Integrationen mit externen Systemen konzipiert." },
      { id: "C", text: "Nur benutzerdefinierte KI-Agenten können Antworten auf organisatorische Daten stützen." },
      { id: "D", text: "Benutzerdefinierte Agenten sind nur über das Copilot Studio-Portal zugänglich, während Copilot in Apps eingebettet ist." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-54",
    topicId: "copilot-grundlagen",
    prompt: "Ein Abteilungsleiter hat einen hochwirksamen, komplexen Microsoft 365 Copilot- Prompt zur Analyse wöchentlicher Verkaufsdaten entwickelt. Der Leiter möchte, dass alle 30 Mitglieder seines Verkaufsteams einfachen und konsistenten Zugriff auf diese spezielle Prompt-Vorlage haben. Welche Methode wird empfohlen, um sicherzustellen, dass diese wertvolle Vorlage vom gesamten Team einheitlich verwendet wird?",
    options: [
      { id: "A", text: "Verwenden Sie die Copilot Studio-Oberfläche, um den Prompt als neuen Agenten zu veröffentlichen." },
      { id: "B", text: "Senden Sie den Text des Prompts per E-Mail an das Team und weisen Sie sie an, ihn in ihrem persönlichen OneDrive zu speichern." },
      { id: "C", text: "Teilen Sie die Prompt-Vorlage direkt aus der Microsoft 365 Copilot Prompt- Bibliothek." },
      { id: "D", text: "Erstellen Sie einen Power Automate-Flow, der den Prompt wöchentlich ausführt." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-55",
    topicId: "copilot-grundlagen",
    prompt: "Sie bewerten Microsoft Purview-Lösungen. Wählen Sie für jede der folgenden Aussagen \"Ja\" aus, wenn die Aussage zutrifft. Andernfalls wählen Sie \"Nein\".",
    statements: [
      { text: "Eine Richtlinie zur Kommunikations-Compliance kann unangemessene Texte in Microsoft Teams-Nachrichten erkennen", correct: "Ja" },
      { text: "Eine Richtlinie zur Kommunikations-Compliance kann anstößige Sprache in Microsoft 365 Copilot-Eingabeaufforderungen erkennen", correct: "Ja" },
      { text: "Eine Richtlinie zur Kommunikations-Compliance kann verwendet werden, um E-Mail-Nachrichten 10 Jahre lang aufzubewahren", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-56",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Aus der Copilot-Prompt-Galerie können Sie einen gespeicherten Prompt bearbeiten", correct: "Ja" },
      { text: "Aus der Copilot-Prompt-Galerie können Sie einen gespeicherten Prompt mit einem Microsoft Teams-Team teilen", correct: "Ja" },
      { text: "Sie können einen freigegebenen Link für einen Prompt erstellen, der NICHT in der Copilot-Prompt-Galerie gespeichert wurde", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-57",
    topicId: "sicherheit-identitaet",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie stellen fest, dass sich einige Benutzer nicht bei Microsoft 365 anmelden können. Sie müssen die fehlgeschlagenen Microsoft 365-Anmeldeversuche anzeigen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das Microsoft Defender-Portal" },
      { id: "B", text: "Das Microsoft Entra Admin Center" },
      { id: "C", text: "Das Microsoft Purview-Portal" },
      { id: "D", text: "Das Microsoft 365 Admin Center" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-58",
    topicId: "sicherheit-identitaet",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement, das eine Microsoft SharePoint-Website namens Site1 enthält. Sie müssen verhindern, dass Benutzer die Inhalte von Site1 mit externen Benutzern teilen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Die Inhalte von Site1" },
      { id: "B", text: "Das SharePoint-Admincenter" },
      { id: "C", text: "Das Microsoft 365-Admincenter" },
      { id: "D", text: "Das Microsoft Entra-Admincenter" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-59",
    topicId: "sicherheit-identitaet",
    prompt: "Welche Aussage beschreibt Microsoft Defender XDR korrekt?",
    options: [
      { id: "A", text: "Microsoft Defender XDR ist eine einheitliche Unternehmenssuite, die Erkennung, Prävention, Untersuchung und Reaktion über Endpunkte, Identitäten, E-Mail und Anwendungen koordiniert, um integrierten Schutz gegen ausgeklügelte Angriffe zu bieten." },
      { id: "B", text: "Microsoft Entra Conditional Access ist eine einheitliche Unternehmenssuite, die Erkennung, Prävention, Untersuchung und Reaktion über Endpunkte, Identitäten, E-Mail und Anwendungen koordiniert, um integrierten Schutz gegen ausgeklügelte Angriffe zu bieten." },
      { id: "C", text: "Microsoft Entra ID Protection ist eine einheitliche Unternehmenssuite, die Erkennung, Prävention, Untersuchung und Reaktion über Endpunkte, Identitäten, E-Mail und Anwendungen koordiniert, um integrierten Schutz gegen ausgeklügelte Angriffe zu bieten." },
      { id: "D", text: "Microsoft Purview ist eine einheitliche Unternehmenssuite, die Erkennung, Prävention, Untersuchung und Reaktion über Endpunkte, Identitäten, E-Mail und Anwendungen koordiniert, um integrierten Schutz gegen ausgeklügelte Angriffe zu bieten." },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-60",
    topicId: "copilot-grundlagen",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Ein Benutzer namens Alex Wilber ist wie in der folgenden Abbildung gezeigt einer Administratorrolle zugewiesen.",
    options: [
      { id: "A", text: "Alex Wilber kann alle Benutzer im Microsoft Entra-Mandanten anzeigen." },
      { id: "B", text: "Alex Wilber kann alle Inhalte auf Microsoft SharePoint-Websites anzeigen." },
      { id: "C", text: "Alex Wilber kann alle Inhalte in Microsoft Exchange-Postfächern lesen." },
      { id: "D", text: "Alex Wilber kann eDiscovery von Microsoft 365 Copilot-Eingabeaufforderungen durchführen." },
    ],
    correct: "A",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-61",
    topicId: "sicherheit-identitaet",
    prompt: "Wählen Sie für jede der folgenden Aussagen \"Ja\", wenn die Aussage zutrifft. Andernfalls wählen Sie \"Nein\". (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Sie können eine Microsoft Entra-Sicherheitsgruppe verwenden, um Berechtigungen für Microsoft Entra ID-Ressourcen zuzuweisen", correct: "Ja" },
      { text: "Sie können eine Microsoft Entra-Sicherheitsgruppe verwenden, um Microsoft 365-Lizenzen zuzuweisen", correct: "Ja" },
      { text: "Sie können eine Microsoft Entra-Sicherheitsgruppe verwenden, um Berechtigungen für Microsoft Exchange-Postfächer zuzuweisen", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-62",
    topicId: "sicherheit-identitaet",
    prompt: "Welche Aussage beschreibt die Autorisierung in Microsoft 365 genau?",
    options: [
      { id: "A", text: "Ein Prozess zur Überprüfung, ob eine Identität tatsächlich diejenige ist, die sie vorgibt zu sein" },
      { id: "B", text: "Ein Prozess, der zusätzliche Authentifizierungsmethoden verlangt, bevor eine Identität auf Ressourcen zugreifen kann" },
      { id: "C", text: "Ein Prozess zur Überprüfung, ob einer Identität der Zugriff auf eine Ressource erlaubt ist" },
      { id: "D", text: "Ein Prozess zur Validierung einer Identität aus einem externen System" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-63",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede korrekte Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Ein Mitglied einer Microsoft SharePoint-Website kann Benutzer einladen, auf die Inhalte der Website zuzugreifen", correct: "Ja" },
      { text: "Ein Websitebesitzer einer Microsoft SharePoint-Website kann Microsoft 365- Gruppen als Mitglieder der Website hinzufügen", correct: "Ja" },
      { text: "Ein Websitebesitzer einer Microsoft SharePoint-Website kann einen anderen Websitebesitzer von der Website entfernen", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-64",
    topicId: "verwaltung-governance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Welche zwei Aufgaben können Sie mithilfe des Exchange-Verwaltungscenters ausführen? (Jede richtige Antwort bildet einen Teil der Lösung. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Zuweisen einer Microsoft Exchange-Lizenz." },
      { id: "B", text: "Erstellen einer Mailflussregel." },
      { id: "C", text: "Erstellen eines freigegebenen Postfachs." },
      { id: "D", text: "Hinzufügen einer benutzerdefinierten Domain." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-65",
    topicId: "sicherheit-identitaet",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "In Microsoft Entra Privileged Identity Management (PIM) hat ein Administrator Sie für die Rolle des Benutzeradministrators berechtigt. Bevor Sie ein Benutzerkonto erstellen können, müssen Sie die Rolle aktivieren." },
      { id: "B", text: "In Microsoft Entra Privileged Identity Management (PIM) hat ein Administrator Sie für die Rolle des Benutzeradministrators berechtigt. Bevor Sie ein Benutzerkonto erstellen können, müssen Sie die Microsoft Authenticator-App installieren." },
      { id: "C", text: "In Microsoft Entra Privileged Identity Management (PIM) hat ein Administrator Sie für die Rolle des Benutzeradministrators berechtigt. Bevor Sie ein Benutzerkonto erstellen können, müssen Sie eine Lizenz anfordern." },
      { id: "D", text: "In Microsoft Entra Privileged Identity Management (PIM) hat ein Administrator Sie für die Rolle des Benutzeradministrators berechtigt. Bevor Sie ein Benutzerkonto erstellen können, müssen Sie Ihre Standortinformationen aktualisieren." },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-66",
    topicId: "sicherheit-identitaet",
    prompt: "Sie öffnen das Microsoft Entra Admin Center wie in der folgenden Abbildung gezeigt. A Das Beheben der Empfehlung 'Passwörter nicht ablaufen lassen' wird den Identity Secure Score am meisten verbessern. B Das Beheben der Empfehlung 'Verwenden von Administrationsrollen mit minimalen Rechten' wird den Identity Secure Score am meisten verbessern. C Das Beheben der Empfehlung 'Richtlinie zur Blockierung von veralteter Authentifizierung aktivieren' wird den Identity Secure Score am meisten verbessern. D Das Beheben der Empfehlung 'Multifaktor-Authentifizierung für Verwaltungsrollen erforderlich machen' wird den Identity Secure Score am meisten verbessern.",
    options: [
      { id: "B", text: "Das Beheben der Empfehlung 'Verwenden von Administrationsrollen mit minimalen Rechten' wird den Identity Secure Score am meisten verbessern." },
      { id: "C", text: "Das Beheben der Empfehlung 'Richtlinie zur Blockierung von veralteter Authentifizierung aktivieren' wird den Identity Secure Score am meisten verbessern." },
      { id: "D", text: "Das Beheben der Empfehlung 'Multifaktor-Authentifizierung für Verwaltungsrollen erforderlich machen' wird den Identity Secure Score am meisten verbessern." },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-67",
    topicId: "sicherheit-identitaet",
    prompt: "Womit können Sie ein Benutzerkonto automatisch sperren, wenn eine riskante Anmeldung erkannt wird?",
    options: [
      { id: "A", text: "Microsoft Defender für Identity" },
      { id: "B", text: "Microsoft Entra ID-Schutz" },
      { id: "C", text: "Microsoft Defender für Office 365" },
      { id: "D", text: "Microsoft Entra Privileged Identity Management (PIM)" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-68",
    topicId: "sicherheit-identitaet",
    prompt: "Sie überprüfen die Sicherheitsrichtlinien Ihres Unternehmens im Rahmen einer Zero-Trust-Strategie. Welche Aussage beschreibt die Zero-Trust-Prinzipien genau?",
    options: [
      { id: "A", text: "Zero Trust verbessert die Benutzererfahrung, indem Authentifizierungsaufforderungen minimiert werden." },
      { id: "B", text: "Zero Trust geht von einem Sicherheitsvorfall aus und überprüft jede Anforderung." },
      { id: "C", text: "Zero Trust behandelt alle Anfragen aus Ihrem Firmennetzwerk als vertrauenswürdig." },
      { id: "D", text: "Zero Trust entfernt die Notwendigkeit, Zugriffsberechtigungen regelmäßig zu überprüfen und anzupassen." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-69",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen einen Bericht erstellen, der die Berechtigungen und aktiven Freigabelinks von Inhalten zeigt, die in Microsoft OneDrive-Konten gespeichert sind. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Überwachung im Microsoft Defender-Portal" },
      { id: "B", text: "Berichte im Microsoft 365 Admin Center" },
      { id: "C", text: "Datenzugriffsverwaltung im SharePoint Admin Center" },
      { id: "D", text: "eDiscovery im Microsoft Purview-Portal" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-70",
    topicId: "copilot-grundlagen",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Eingabeaufforderungen und Antworten, die von Benutzern in Microsoft 365 Copilot ausgegeben werden, werden von Microsoft zum Trainieren von Modellen verwendet", correct: "Nein" },
      { text: "Von Microsoft Graph abgerufene Inhalte werden von Microsoft zum Trainieren von Modellen verwendet", correct: "Nein" },
      { text: "Microsoft 365 Copilot respektiert die Sicherheitsberechtigungen in Ihrem Microsoft 365-Abonnement", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-71",
    topicId: "copilot-agenten",
    prompt: "Ihr Unternehmen verwendet die Abrechnung nach Verbrauch (Pay-as-you-go) für Microsoft 365 Copilot. Das Unternehmen möchte eine bessere Übersicht über die Copilot-Nutzungskosten und die Möglichkeit, die Ausgaben der Abteilungen vorherzusagen. Sie müssen sicherstellen, dass Sie die Copilot-Kosten nach Abteilung einsehen können. Was sollten Sie verwenden? (Um zu antworten, wählen Sie die entsprechenden Optionen im Antwortbereich aus. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Portal: Das Microsoft 365 Admin Center Funktion: Eine Abrechnungsrichtlinie" },
      { id: "B", text: "Portal: Das Microsoft 365 Admin Center Funktion: Ein Copilot-Connector" },
      { id: "C", text: "Portal: Das Microsoft Entra Admin Center Funktion: Eine Auto-Claim-Richtlinie" },
      { id: "D", text: "Portal: Das Microsoft Entra Admin Center Funktion: Eine Abrechnungsrichtlinie" },
      { id: "E", text: "Portal: Das Microsoft Purview-Portal Funktion: Ein Copilot-Connector" },
      { id: "F", text: "Portal: Das Microsoft Purview-Portal Funktion: Eine Auto-Claim-Richtlinie" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-72",
    topicId: "copilot-agenten",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Benutzer, denen eine Microsoft 365 E5-Lizenz zugewiesen ist, können keine auf dem Web basierenden Microsoft 365 Copilot-Agenten erstellen", correct: "Nein" },
      { text: "Benutzer müssen eine Microsoft 365 Copilot-Lizenz zugewiesen bekommen, um den Analyst-Agenten zu verwenden", correct: "Ja" },
      { text: "Benutzer können eine natürliche Sprachaufforderung verwenden, um einen Microsoft 365 Copilot-Agenten zu erstellen", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-73",
    topicId: "purview-compliance",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Sie können die Audit Microsoft Purview-Lösung verwenden, um alle Inhalte zu finden, die sich auf den Begriff \"Project Falcon\" in den E-Mails beziehen, die zwischen zwei Benutzern ausgetauscht wurden." },
      { id: "B", text: "Sie können die Data Catalog Microsoft Purview-Lösung verwenden, um alle Inhalte zu finden, die sich auf den Begriff \"Project Falcon\" in den E-Mails beziehen, die zwischen zwei Benutzern ausgetauscht wurden." },
      { id: "C", text: "Sie können die eDiscovery Microsoft Purview-Lösung verwenden, um alle Inhalte zu finden, die sich auf den Begriff \"Project Falcon\" in den E-Mails beziehen, die zwischen zwei Benutzern ausgetauscht wurden." },
      { id: "D", text: "Sie können die Insider Risk Management Microsoft Purview-Lösung verwenden, um alle Inhalte zu finden, die sich auf den Begriff \"Project Falcon\" in den E-Mails beziehen, die zwischen zwei Benutzern ausgetauscht wurden." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-74",
    topicId: "purview-compliance",
    prompt: "Ihr Unternehmen verwendet Microsoft Purview Data Loss Prevention (DLP)- Richtlinien. Ein Benutzer namens User1 teilt sensible Informationen mit einem externen Benutzer über Microsoft Teams. Sie müssen die geteilten sensiblen Inhalte identifizieren. Was sollten Sie im Microsoft Purview-Portal verwenden?",
    options: [
      { id: "A", text: "Diagnosen" },
      { id: "B", text: "Daten-Explorer" },
      { id: "C", text: "Inhalts-Explorer" },
      { id: "D", text: "Aktivitäts-Explorer" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-75",
    topicId: "verwaltung-governance",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie Nein. (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Zero Trust erfordert ein Azure-Abonnement", correct: "Nein" },
      { text: "Zero Trust ist eine Sicherheitsstrategie, KEIN spezifisches Produkt", correct: "Ja" },
      { text: "Über das Microsoft 365 Admin Center können Sie Zero Trust für Ihre Organisation aktivieren", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-76",
    topicId: "copilot-grundlagen",
    prompt: "Wählen Sie die Antwort, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Microsoft Copilot Studio enthält Signale wie Zusammenarbeitsverlauf, Dokumentenrelevanz und Kommunikationshäufigkeit, die die Antworten von Microsoft 365 Copilot beeinflussen." },
      { id: "B", text: "Microsoft Graph enthält Signale wie Zusammenarbeitsverlauf, Dokumentenrelevanz und Kommunikationshäufigkeit, die die Antworten von Microsoft 365 Copilot beeinflussen." },
      { id: "C", text: "Microsoft Purview enthält Signale wie Zusammenarbeitsverlauf, Dokumentenrelevanz und Kommunikationshäufigkeit, die die Antworten von Microsoft 365 Copilot beeinflussen." },
      { id: "D", text: "Microsoft Viva Insights enthält Signale wie Zusammenarbeitsverlauf, Dokumentenrelevanz und Kommunikationshäufigkeit, die die Antworten von Microsoft 365 Copilot beeinflussen." },
    ],
    correct: "B",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-77",
    topicId: "sicherheit-identitaet",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage zutrifft. Andernfalls wählen Sie Nein. (HINWEIS: Jede korrekte Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Benutzer können Microsoft 365 Copilot anonym verwenden", correct: "Nein" },
      { text: "Administratoren können den Selbstkauf von Microsoft 365 Copilot-Lizenzen erlauben", correct: "Ja" },
      { text: "Microsoft 365 Copilot-Lizenzen können an Microsoft Entra ID-Gastbenutzer aus anderen Organisationen zugewiesen werden", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-78",
    topicId: "purview-compliance",
    prompt: "Discover and classify sensitive data across multiple platforms: Insider Risk Management Block users from sharing intellectual property with external users: Data Loss Prevention Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Sie müssen Microsoft Purview verwenden, um die folgenden Anforderungen zu erfüllen: • Sensible Daten auf mehreren Plattformen entdecken und klassifizieren. • Benutzer daran hindern, geistiges Eigentum mit externen Benutzern zu teilen. Welche Microsoft Purview-Lösung sollten Sie für jede Anforderung verwenden? (Um zu antworten, wählen Sie die entsprechenden Optionen im Antwortbereich aus. HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    options: [
      { id: "A", text: "Sensible Daten auf mehreren Plattformen entdecken und klassifizieren: Kommunikations-Compliance Benutzer daran hindern, geistiges Eigentum mit externen Benutzern zu teilen: Data Loss Prevention" },
      { id: "B", text: "Sensible Daten auf mehreren Plattformen entdecken und klassifizieren: Data Loss Prevention Benutzer daran hindern, geistiges Eigentum mit externen Benutzern zu teilen: Information Protection" },
      { id: "C", text: "Discover and classify sensitive data across multiple platforms: Data Loss Prevention Block users from sharing intellectual property with external users: Insider Risk Management" },
      { id: "D", text: "Discover and classify sensitive data across multiple platforms: Information Protection Block users from sharing intellectual property with external users: Communication Compliance" },
      { id: "E", text: "Discover and classify sensitive data across multiple platforms: Information Protection Block users from sharing intellectual property with external users: Insider Risk Management" },
      { id: "F", text: "Discover and classify sensitive data across multiple platforms: Insider Risk Management Block users from sharing intellectual property with external users: Data Loss Prevention" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-79",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365 E5-Abonnement. Sie müssen verhindern, dass Benutzer unternehmensinterne Finanzdaten an externe Benutzer weitergeben. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Rollengruppen" },
      { id: "B", text: "Richtlinien zur Verhinderung von Datenverlusten (DLP)" },
      { id: "C", text: "Richtlinien zum Insider-Risikomanagement" },
      { id: "D", text: "Aufbewahrungsbezeichnungen" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-80",
    topicId: "purview-compliance",
    prompt: "Sie müssen Dateien und E-Mails identifizieren, die Sozialversicherungsnummern (SSNs) und Kreditkartennummern enthalten. Was sollten Sie im Microsoft Purview-Portal verwenden?",
    options: [
      { id: "A", text: "Daten-Explorer" },
      { id: "B", text: "Berichte zum Informationsschutz" },
      { id: "C", text: "Richtlinien zum Informationsschutz" },
      { id: "D", text: "Aktivitäts-Explorer" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-81",
    topicId: "purview-compliance",
    prompt: "Wählen Sie die Antwort aus, die den Satz richtig vervollständigt.",
    options: [
      { id: "A", text: "Microsoft Purview-Vertraulichkeitskennzeichnungen können auf Azure Blob Storage angewendet werden." },
      { id: "B", text: "Microsoft Purview-Vertraulichkeitskennzeichnungen können auf Microsoft 365 Copilot-Konversationen angewendet werden." },
      { id: "C", text: "Microsoft Purview-Vertraulichkeitskennzeichnungen können auf Microsoft SharePoint-Websites angewendet werden." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-82",
    topicId: "purview-compliance",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Mit der eingeschränkten SharePoint-Suche können Sie den Administratorzugriff auf Microsoft SharePoint-Websites einschränken, ohne dass Benutzer daran gehindert werden, auf die Dateien und Inhalte zuzugreifen, für die sie über Berechtigungen verfügen." },
      { id: "B", text: "Mit der eingeschränkten SharePoint-Suche können Sie den Zugriff von Gastbenutzern auf Microsoft SharePoint-Websites einschränken, ohne dass Benutzer daran gehindert werden, auf die Dateien und Inhalte zuzugreifen, für die sie über Berechtigungen verfügen." },
      { id: "C", text: "Mit der eingeschränkten SharePoint-Suche können Sie den Zugriff von Microsoft 365 Copilot auf Microsoft SharePoint-Websites einschränken, ohne dass Benutzer daran gehindert werden, auf die Dateien und Inhalte zuzugreifen, für die sie Berechtigungen besitzen." },
      { id: "D", text: "Mit der eingeschränkten SharePoint-Suche können Sie den Zugriff von Microsoft Purview eDiscovery auf Microsoft SharePoint-Websites einschränken, ohne dass Benutzer daran gehindert werden, auf die Dateien und Inhalte zuzugreifen, für die sie Berechtigungen besitzen." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-83",
    topicId: "purview-compliance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365 E5-Abonnement. Sie erstellen eine Microsoft Purview-Vertraulichkeitskennzeichnung mit dem Namen „Label1“. Sie müssen sicherstellen, dass Benutzer „Label1“ auf Dateien in Microsoft 365 anwenden können. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Eine Richtlinie für Vertraulichkeitskennzeichnungen" },
      { id: "B", text: "Einen trainierbaren Klassifikator" },
      { id: "C", text: "Eine Richtlinie für Aufbewahrungskennzeichnungen" },
      { id: "D", text: "Eine Richtlinie für die automatische Kennzeichnung" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-84",
    topicId: "purview-compliance",
    prompt: "Ihr Unternehmen verfügt über eine schriftliche Compliance-Richtlinie, wonach alle E-Mails sieben Jahre lang aufbewahrt und anschließend endgültig gelöscht werden müssen. Welche Microsoft Purview-Lösung sollten Sie verwenden?",
    options: [
      { id: "A", text: "Informationsschutz" },
      { id: "B", text: "Datenlebenszyklusmanagement" },
      { id: "C", text: "Schutz vor Datenverlust" },
      { id: "D", text: "Insider-Risikomanagement" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-85",
    topicId: "copilot-grundlagen",
    prompt: "Wählen Sie die Antwort aus, die den Satz korrekt vervollständigt.",
    options: [
      { id: "A", text: "Im Microsoft 365-Admincenter zeigt die Kennzahl „Verwendete Credits“ im Copilot-Credits-Bericht die Gesamtzahl der Credits an, die von Benutzern in Ihrer Organisation verbraucht wurden, die Microsoft Teams nutzen und mit arbeitsbasierten Agenten im Microsoft 365 Copilot-Chat interagieren." },
      { id: "B", text: "Im Microsoft 365 Admin Center zeigt die Metrik „Verwendete Credits“ im Copilot-Credits-Bericht die Gesamtzahl der Credits an, die von Benutzern in Ihrer Organisation verbraucht wurden, die nicht zu Ihrer Organisation gehören und mit geschäftlichen Agenten im Microsoft 365 Copilot Chat interagieren." },
      { id: "C", text: "Im Microsoft 365-Admincenter zeigt die Metrik „Verwendete Credits“ im Copilot-Credits-Bericht die Gesamtzahl der Credits an, die von Benutzern in Ihrer Organisation verbraucht wurden, denen eine Microsoft 365 Copilot-Lizenz zugewiesen ist und die mit arbeitsbasierten Agenten im Microsoft 365 Copilot- Chat interagieren." },
      { id: "D", text: "Im Microsoft 365-Admincenter zeigt die Metrik „Verwendete Credits“ im Copilot-Credits-Bericht die Gesamtzahl der Credits an, die von Benutzern in Ihrer Organisation verwendet wurden, denen KEINE Microsoft 365 Copilot-Lizenz zugewiesen ist und die mit arbeitsbasierten Agenten in Microsoft 365 Copilot Chat interagieren." },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-86",
    topicId: "copilot-grundlagen",
    prompt: "Sie haben eine Microsoft SharePoint-Website namens „Site1“ und eine Sicherheitsgruppe namens „Group1“. Sie möchten verhindern, dass alle Benutzer, die derzeit Zugriff auf „Site1“ haben, auf die Inhalte der Website zugreifen können, es sei denn, der Benutzer ist auch Mitglied der Gruppe „Group1“. Welche Einstellungen sollten Sie konfigurieren? (Wählen Sie zur Beantwortung die entsprechenden Einstellungen im Antwortbereich aus.)",
    options: [
      { id: "A", text: "E-Mail" },
      { id: "B", text: "Datenschutz" },
      { id: "C", text: "Externe Dateifreigabe" },
      { id: "D", text: "Vertraulichkeitsbezeichnung" },
      { id: "E", text: "Erkennung von Inhalten einschränken" },
      { id: "F", text: "Eingeschränkter Zugriff auf die Website" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-87",
    topicId: "purview-compliance",
    prompt: "Microsoft 365 Copilot honors Microsoft Purview sensitivity labels: No Microsoft 365 Copilot ignores Microsoft Purview data loss prevention (DLP) policies: No Microsoft 365 Copilot honors existing Microsoft 365 permissions: No Wählen Sie für jede der folgenden Aussagen „Ja“, wenn die Aussage wahr ist. Andernfalls wählen Sie „Nein“. (HINWEIS: Jede richtige Auswahl bringt einen Punkt.)",
    statements: [
      { text: "Microsoft 365 Copilot berücksichtigt die Vertraulichkeitskennzeichnungen von Microsoft Purview", correct: "Ja" },
      { text: "Microsoft 365 Copilot ignoriert die Richtlinien zur Verhinderung von Datenverlusten (DLP) von Microsoft Purview", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-88",
    topicId: "purview-compliance",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie \"Nein\". (HINWEIS: Jede richtige Auswahl ist einen Punkt wert.)",
    statements: [
      { text: "Eine Vertraulichkeitskennzeichnung kann auf eine Microsoft SharePoint-Website angewendet werden", correct: "Ja" },
      { text: "Eine Vertraulichkeitskennzeichnung kann auf eine E-Mail-Nachricht in Microsoft Exchange angewendet werden", correct: "Ja" },
      { text: "Eine Vertraulichkeitskennzeichnung kann auf Windows 11-Geräte angewendet werden", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-89",
    topicId: "copilot-grundlagen",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Ihr Unternehmen hat kürzlich Microsoft 365 Copilot-Lizenzen für einige Benutzer erworben. Sie müssen ermitteln, wie viele nicht lizenzierte Benutzer Copilot in Microsoft Teams genutzt haben. Welchen Nutzungsbericht sollten Sie im Microsoft 365 Admin Center verwenden?",
    options: [
      { id: "A", text: "Microsoft 365 Copilot Chat" },
      { id: "B", text: "Microsoft 365 Copilot Search" },
      { id: "C", text: "Microsoft 365 Apps" },
      { id: "D", text: "Microsoft 365 Copilot" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-90",
    topicId: "copilot-grundlagen",
    prompt: "Ein Benutzer namens „User1“ ist für die vierteljährliche Umsatzberichterstattung zuständig. „User1“ muss Leistungstrends erkennen, visuelle Erkenntnisse gewinnen und eine Zusammenfassung von Anomalien über mehrere Dateien hinweg erstellen, die verschiedene Datensätze enthalten. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Den „Analyst“-Agenten in Microsoft 365 Copilot" },
      { id: "B", text: "Den „Researcher“-Agenten in Microsoft 365 Copilot" },
      { id: "C", text: "Die Microsoft 365 Copilot-Suche" },
      { id: "D", text: "Copilot in Excel" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-91",
    topicId: "copilot-agenten",
    prompt: "Ihr Unternehmen prüft derzeit die Lizenzierung von Microsoft 365 Copilot. In welchem Szenario sollten Sie die nutzungsabhängige Abrechnung nutzen?",
    options: [
      { id: "A", text: "Um Benutzern Zugriff auf den KI-Assistenten in Copilot in Word zu gewähren" },
      { id: "B", text: "Um die Aktionen in Microsoft Teams-Besprechungen zusammenzufassen" },
      { id: "C", text: "Um Bilder in Premium-Chats zu generieren" },
      { id: "D", text: "Um nicht lizenzierten Benutzern einen benutzerdefinierten Agenten zur Verfügung zu stellen" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    id: "real-ab900-92",
    topicId: "copilot-grundlagen",
    prompt: "Sie verwenden Microsoft 365 Copilot. Sie möchten eine Eingabeaufforderung so planen, dass sie um Mitternacht ausgeführt wird. Welche Aufgabe sollten Sie in Ihre Lösung aufnehmen?",
    options: [
      { id: "A", text: "Einen Agenten erstellen." },
      { id: "B", text: "Ein Notizbuch erstellen." },
      { id: "C", text: "Die Eingabeaufforderung ausführen." },
      { id: "D", text: "Die Eingabeaufforderung speichern." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-93",
    topicId: "copilot-grundlagen",
    prompt: "Ihr Unternehmen plant den Einsatz von Microsoft 365 Copilot. Sie müssen einem Benutzer die Möglichkeit geben, Microsoft 365 Copilot zu nutzen, einschließlich der Agenten „Researcher“ und „Analyst“. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das Microsoft 365 Admin Center" },
      { id: "B", text: "Das Microsoft Purview-Portal" },
      { id: "C", text: "Das Microsoft Entra Admin Center" },
      { id: "D", text: "Das Microsoft Defender-Portal" },
    ],
    correct: "A",
    explanation: "",
  },
  {
    id: "real-ab900-94",
    topicId: "copilot-grundlagen",
    prompt: "Ihr Unternehmen erwägt, Microsoft 365 Copilot auf Pay-as-you-go-Basis zu nutzen, anstatt eine Microsoft 365 Copilot-Lizenz zu erwerben. In welchem Szenario kommt die Pay-as-you-go-Abrechnung in Frage?",
    options: [
      { id: "A", text: "Durchführung einer mehrstufigen Schlussfolgerung mithilfe des Researcher- Agenten" },
      { id: "B", text: "Erstellung einer Zusammenfassung eines Microsoft Teams-Meetings" },
      { id: "C", text: "Verwendung eines benutzerdefinierten Agenten, der auf Arbeitsdaten basiert" },
      { id: "D", text: "Verwendung des KI-Assistenten zum Bearbeiten eines Dokuments in Copilot in Word" },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-95",
    topicId: "copilot-grundlagen",
    prompt: "Ihr Unternehmen verfügt über eine Microsoft SharePoint-Website namens „Site1“. „Site1“ enthält alle Richtlinien der Personalabteilung des Unternehmens. Die Richtlinien sind als Microsoft Word-Dokumente gespeichert. Alle Benutzer haben Lesezugriff auf „Site1“. Der Leiter der Personalabteilung berichtet, dass Benutzeranfragen zu den Richtlinien NICHT zeitnah bearbeitet werden, insbesondere im Umfeld wichtiger Feiertage. Sie müssen eine Lösung vorschlagen, die es den Benutzern ermöglicht, die Richtlinien der Personalabteilung zu finden. Die Lösung muss den Benutzern eine Liste häufiger Fragen bereitstellen und sicherstellen, dass die Antworten ausschließlich auf Site1 basieren. Was sollten Sie in die Empfehlung aufnehmen?",
    options: [
      { id: "A", text: "Den persönlichen Assistenten in Copilot in Word" },
      { id: "B", text: "Einen benutzerdefinierten Microsoft 365 Copilot-Agenten" },
      { id: "C", text: "Den Researcher-Agenten in Microsoft 365 Copilot" },
      { id: "D", text: "Ein Microsoft 365 Copilot-Notizbuch" },
    ],
    correct: "B",
    explanation: "",
  },
  {
    id: "real-ab900-96",
    topicId: "purview-compliance",
    prompt: "Wählen Sie die Antwort aus, die den Satz richtig vervollständigt.",
    options: [
      { id: "A", text: "Über das Microsoft Purview-Portal können Sie mit dem Data Explorer Datenschutzrichtlinien erstellen und verwalten." },
      { id: "B", text: "Über das Microsoft Purview-Portal können Sie mit dem Data Explorer nach Inhalten in Postfächern und Websites suchen." },
      { id: "C", text: "Über das Microsoft Purview-Portal können Sie mit dem Data Explorer sensible Informationen identifizieren und deren Speicherorte ermitteln." },
      { id: "D", text: "Über das Microsoft Purview-Portal können Sie den Data Explorer verwenden, um die Wirksamkeit Ihrer Richtlinien zur Verhinderung von Datenverlusten (DLP) zu überprüfen." },
    ],
    correct: "C",
    explanation: "",
  },
  {
    id: "real-ab900-97",
    topicId: "verwaltung-governance",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement, das eine Microsoft SharePoint-Website namens „Site1“ enthält. Sie müssen alle Änderungen ermitteln, die ein Websiteadministrator an den Websiteeinstellungen von „Site1“ vorgenommen hat. Welchen Bericht sollten Sie im SharePoint-Verwaltungscenter verwenden? (Wählen Sie zur Beantwortung den entsprechenden Bericht im Antwortbereich aus.)",
    options: [
      { id: "A", text: "Agent Insights" },
      { id: "B", text: "App Insights Katalogverwaltung" },
      { id: "D", text: "Änderungshistorie" },
      { id: "E", text: "Datenzugriffs-Governance" },
      { id: "F", text: "OneDrive-Konten" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-98",
    topicId: "purview-compliance",
    prompt: "Für jede der folgenden Aussagen wählen Sie Ja, wenn die Aussage wahr ist. Andernfalls wählen Sie \"Nein\". (HINWEIS: Jede richtige Auswahl bringt einen Punkt.)",
    statements: [
      { text: "Microsoft Purview Communications Compliance kann beleidigende Texte in Bildern erkennen, die auf Microsoft SharePoint-Websites gespeichert sind", correct: "Ja" },
      { text: "Microsoft Purview Communications Compliance anonymisiert Benutzeridentitäten standardmäßig während Untersuchungen", correct: "Ja" },
      { text: "Microsoft Purview Communications Compliance fügt allen überwachten Kommunikationen einen Haftungsausschluss hinzu", correct: "Nein" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-99",
    topicId: "sicherheit-identitaet",
    prompt: "Ihre Organisation verfügt über ein Microsoft 365-Abonnement. Allen Benutzern wurde eine Microsoft 365 Copilot-Lizenz zugewiesen. Sie müssen verhindern, dass die Benutzer mit Copilot Bilder erstellen. Was sollten Sie verwenden?",
    options: [
      { id: "A", text: "Das Microsoft Defender-Portal" },
      { id: "B", text: "Das Microsoft Entra Admin Center" },
      { id: "C", text: "Das Microsoft Purview-Portal" },
      { id: "D", text: "Das Microsoft 365 Admin Center" },
    ],
    correct: "D",
    explanation: "",
  },
  {
    type: "yesno",
    id: "real-ab900-100",
    topicId: "copilot-grundlagen",
    prompt: "Wählen Sie für jede der folgenden Aussagen „Ja\", wenn die Aussage wahr ist. Andernfalls wählen Sie „Nein\". (HINWEIS: Jede richtige Auswahl bringt einen Punkt.)",
    statements: [
      { text: "Administratoren können bestimmte Websites für die Nutzung durch Microsoft 365 Copilot sperren", correct: "Ja" },
      { text: "Administratoren können Microsoft 365 Copilot daran hindern, bei der Beantwortung von Benutzeranfragen die Websuche zu nutzen", correct: "Ja" },
      { text: "Administratoren können den Zugriff auf den Researcher-Agenten in Microsoft 365 Copilot sperren, während sie den Zugriff auf den Analyst-Agenten zulassen", correct: "Ja" },
    ],
    explanation: "",
  },
  {
    id: "real-ab900-101",
    topicId: "copilot-agenten",
    prompt: "Sie müssen sicherstellen, dass Benutzer ein externes System als Wissensquelle für benutzerdefinierte Microsoft 365 Copilot-Agenten nutzen können. Was sollten Sie im Microsoft 365 Admin Center konfigurieren? (Wählen Sie zur Beantwortung die entsprechenden Einstellungen im Antwortbereich aus.)",
    options: [
      { id: "A", text: "Copilot – Konnektoren" },
      { id: "B", text: "Copilot – Suche" },
      { id: "C", text: "Copilot – Einstellungen" },
      { id: "D", text: "Agenten – Übersicht" },
      { id: "E", text: "Agenten – Tools" },
      { id: "F", text: "Agenten – Einstellungen" },
    ],
    correct: "A",
    explanation: "",
  },
];

// ---------------------------------------------------------------------
// Locale translations. Same pattern as lib/az900Practice.ts's
// getAz900Questions/applyTranslation — see that file for the detailed
// rationale. Each locale file in lib/i18n/questions/ab900.<locale>.ts is
// optional and can be filled in incrementally; any question id not yet
// present in a given locale's file falls back to the German original
// above, so a partially-translated language never shows an empty field.
// ---------------------------------------------------------------------
import type { QuestionTranslations } from "@/lib/i18n/questions/types";
import ab900_en from "@/lib/i18n/questions/ab900.en";
import ab900_fa from "@/lib/i18n/questions/ab900.fa";
import ab900_ar from "@/lib/i18n/questions/ab900.ar";
import ab900_uk from "@/lib/i18n/questions/ab900.uk";
import ab900_es from "@/lib/i18n/questions/ab900.es";
import ab900_fr from "@/lib/i18n/questions/ab900.fr";
import ab900_ru from "@/lib/i18n/questions/ab900.ru";

const AB900_TRANSLATIONS: Partial<Record<string, QuestionTranslations>> = {
  en: ab900_en,
  fa: ab900_fa,
  ar: ab900_ar,
  uk: ab900_uk,
  es: ab900_es,
  fr: ab900_fr,
  ru: ab900_ru,
};

function applyAb900Translation(
  q: PracticeQuestion,
  tr: QuestionTranslations[string] | undefined
): PracticeQuestion {
  if (!tr) return q;
  const merged = { ...q } as PracticeQuestion & { prompt: string; explanation: string };
  if (tr.prompt) merged.prompt = tr.prompt;
  if (tr.explanation) merged.explanation = tr.explanation;
  if (tr.options && "options" in q) {
    (merged as SingleChoiceQuestion).options = (q as SingleChoiceQuestion).options.map((o) => ({
      ...o,
      text: tr.options?.[o.id] ?? o.text,
    }));
  }
  if (tr.statements && q.type === "yesno") {
    (merged as YesNoQuestion).statements = (q as YesNoQuestion).statements.map((s, i) => ({
      ...s,
      text: tr.statements?.[i] ?? s.text,
    }));
  }
  return merged;
}

/** Returns AB900_QUESTIONS with any available translations for the given
 * locale applied. Falls back to German for locales with no translation
 * file yet, and per-question for any field not yet translated. */
export function getAb900Questions(locale: string): PracticeQuestion[] {
  const translations = AB900_TRANSLATIONS[locale];
  if (!translations) return AB900_QUESTIONS;
  return AB900_QUESTIONS.map((q) => applyAb900Translation(q, translations[q.id]));
}