// Data for the /learning-paths page: career-goal cards, their detail panel,
// and the 6-step generic learning journey shown underneath. This is
// presentation data (mirrors the approved design) rather than a live
// progress-tracking system — cert codes referenced here should exist in
// companiesData.ts so links resolve to real certification detail pages.

export type CareerLevel = "Beginner" | "Intermediate" | "Advanced";

export type CareerPath = {
  slug: string;
  title: string;
  icon: "headset" | "desktop" | "monitor" | "server" | "cloud-azure" | "cloud-gcp" | "network" | "shield" | "devops" | "database" | "ai" | "code" | "chart" | "kanban";
  level: CareerLevel;
  duration: string; // e.g. "3–6 Monate"
  salaryRange: string; // e.g. "35–45k€"
  demand: "high" | "medium";
  entrySalary: string;
  openJobs: string;
  topCity: string;
  skills: string[];
  // `link` is only set for certs with real, hand-authored content (currently
  // Microsoft). Other vendors' cert pages are still generic placeholder
  // content, so those entries are shown as plain (non-clickable) labels
  // instead of a misleading link to unrelated placeholder text.
  recommendedCerts: { code: string; link?: { companySlug: string; certId: string } }[];
  roadmap: { phase: string; duration: string }[];
};

export const careerPaths: CareerPath[] = [
  {
    slug: "it-support-specialist",
    title: "IT Support Specialist",
    icon: "headset",
    level: "Beginner",
    duration: "3–6 Monate",
    salaryRange: "35–45k€",
    demand: "high",
    entrySalary: "42.000 €",
    openJobs: "8.450+",
    topCity: "Berlin, München",
    skills: [
      "Windows 11 / IT-Support",
      "Active Directory Basics",
      "Microsoft 365",
      "Netzwerk-Grundlagen",
      "Ticketing-Systeme",
      "Hardware-Troubleshooting",
      "Remote-Support",
      "Kommunikation",
    ],
    recommendedCerts: [
      { code: "Microsoft 365 Fundamentals", link: { companySlug: "microsoft", certId: "ms-900" } },
      { code: "CompTIA A+" },
      { code: "CompTIA Network+" },
      { code: "ITIL 4 Foundation" },
    ],
    roadmap: [
      { phase: "IT Support Specialist", duration: "0–2 Jahre" },
      { phase: "Help Desk Technician", duration: "2–4 Jahre" },
      { phase: "System Administrator", duration: "4–6 Jahre" },
      { phase: "IT-Manager / Team Lead", duration: "6+ Jahre" },
    ],
  },
  {
    slug: "help-desk-technician",
    title: "Help Desk Technician",
    icon: "headset",
    level: "Beginner",
    duration: "3–6 Monate",
    salaryRange: "42–55k€",
    demand: "high",
    entrySalary: "45.000 €",
    openJobs: "5.200+",
    topCity: "Hamburg, Berlin",
    skills: [
      "Incident Management",
      "Windows & macOS Support",
      "Active Directory",
      "Remote-Desktop-Tools",
      "SLA-Management",
      "Endpoint-Sicherheit",
    ],
    recommendedCerts: [
      { code: "CompTIA A+" },
      { code: "ITIL 4 Foundation" },
      { code: "Microsoft 365 Fundamentals", link: { companySlug: "microsoft", certId: "ms-900" } },
    ],
    roadmap: [
      { phase: "Help Desk Technician", duration: "0–2 Jahre" },
      { phase: "Desktop Support Engineer", duration: "2–4 Jahre" },
      { phase: "System Administrator", duration: "4–6 Jahre" },
      { phase: "IT-Manager / Team Lead", duration: "6+ Jahre" },
    ],
  },
  {
    slug: "desktop-support-engineer",
    title: "Desktop Support Engineer",
    icon: "desktop",
    level: "Beginner",
    duration: "3–6 Monate",
    salaryRange: "38–48k€",
    demand: "high",
    entrySalary: "43.000 €",
    openJobs: "4.100+",
    topCity: "München, Frankfurt",
    skills: [
      "Hardware-Diagnose",
      "Betriebssystem-Deployment",
      "Endpoint Management",
      "Active Directory Basics",
      "Netzwerk-Grundlagen",
      "Ticketing-Systeme",
    ],
    recommendedCerts: [
      { code: "CompTIA A+" },
      { code: "Windows Server Hybrid Administrator", link: { companySlug: "microsoft", certId: "az-800" } },
      { code: "ITIL 4 Foundation" },
    ],
    roadmap: [
      { phase: "Desktop Support Engineer", duration: "0–2 Jahre" },
      { phase: "System Administrator", duration: "2–5 Jahre" },
      { phase: "Infrastructure Engineer", duration: "5–7 Jahre" },
      { phase: "IT-Manager / Team Lead", duration: "7+ Jahre" },
    ],
  },
  {
    slug: "system-administrator",
    title: "System Administrator",
    icon: "server",
    level: "Intermediate",
    duration: "6–9 Monate",
    salaryRange: "48–68k€",
    demand: "high",
    entrySalary: "52.000 €",
    openJobs: "6.800+",
    topCity: "Berlin, Stuttgart",
    skills: [
      "Windows Server Administration",
      "Active Directory & Group Policy",
      "Virtualisierung (Hyper-V/VMware)",
      "Backup & Disaster Recovery",
      "PowerShell-Scripting",
      "Netzwerk- & Firewall-Grundlagen",
    ],
    recommendedCerts: [
      { code: "Windows Server Hybrid Administrator", link: { companySlug: "microsoft", certId: "az-800" } },
      { code: "Azure Administrator Associate", link: { companySlug: "microsoft", certId: "az-104" } },
      { code: "CompTIA Network+" },
    ],
    roadmap: [
      { phase: "System Administrator", duration: "0–3 Jahre" },
      { phase: "Senior System Administrator", duration: "3–6 Jahre" },
      { phase: "Infrastructure / Cloud Engineer", duration: "6–8 Jahre" },
      { phase: "IT-Manager / Team Lead", duration: "8+ Jahre" },
    ],
  },
  {
    slug: "azure-administrator",
    title: "Azure Administrator",
    icon: "cloud-azure",
    level: "Intermediate",
    duration: "6–12 Monate",
    salaryRange: "50–70k€",
    demand: "high",
    entrySalary: "55.000 €",
    openJobs: "7.300+",
    topCity: "München, Frankfurt",
    skills: [
      "Azure-Identitäten & Governance",
      "Azure Storage & Compute",
      "Virtuelle Netzwerke",
      "Azure Monitor",
      "Kostenmanagement",
      "Infrastructure as Code",
    ],
    recommendedCerts: [
      { code: "Azure Fundamentals", link: { companySlug: "microsoft", certId: "az-900" } },
      { code: "Azure Administrator Associate", link: { companySlug: "microsoft", certId: "az-104" } },
      { code: "Azure Security Engineer Associate", link: { companySlug: "microsoft", certId: "az-500" } },
    ],
    roadmap: [
      { phase: "Azure Administrator", duration: "0–3 Jahre" },
      { phase: "Cloud Engineer", duration: "3–5 Jahre" },
      { phase: "Cloud Solutions Architect", duration: "5–8 Jahre" },
      { phase: "Cloud-Architekt / Lead", duration: "8+ Jahre" },
    ],
  },
  {
    slug: "cloud-engineer",
    title: "Cloud Engineer",
    icon: "cloud-gcp",
    level: "Advanced",
    duration: "12–18 Monate",
    salaryRange: "60–90k€",
    demand: "high",
    entrySalary: "65.000 €",
    openJobs: "9.100+",
    topCity: "Berlin, München",
    skills: [
      "Multi-Cloud-Architektur (Azure/AWS/GCP)",
      "Infrastructure as Code (Terraform)",
      "Container & Kubernetes",
      "CI/CD-Pipelines",
      "Netzwerk- & Sicherheitsdesign",
      "Kostenoptimierung",
    ],
    recommendedCerts: [
      { code: "Azure Solutions Architect Expert", link: { companySlug: "microsoft", certId: "az-305" } },
      { code: "AWS Solutions Architect" },
      { code: "Google Cloud Digital Leader" },
    ],
    roadmap: [
      { phase: "Cloud Engineer", duration: "0–3 Jahre" },
      { phase: "Senior Cloud Engineer", duration: "3–6 Jahre" },
      { phase: "Cloud Solutions Architect", duration: "6–9 Jahre" },
      { phase: "Principal Cloud Architect", duration: "9+ Jahre" },
    ],
  },
  {
    slug: "network-administrator",
    title: "Network Administrator",
    icon: "network",
    level: "Intermediate",
    duration: "6–9 Monate",
    salaryRange: "42–60k€",
    demand: "medium",
    entrySalary: "47.000 €",
    openJobs: "3.900+",
    topCity: "Hamburg, Köln",
    skills: [
      "Routing & Switching",
      "Firewall-Konfiguration",
      "VPN & Netzwerksicherheit",
      "Netzwerk-Monitoring",
      "TCP/IP-Grundlagen",
      "WLAN-Administration",
    ],
    recommendedCerts: [
      { code: "CompTIA Network+" },
      { code: "CCNA 200-301" },
      { code: "Azure Network Engineer Associate", link: { companySlug: "microsoft", certId: "az-700" } },
    ],
    roadmap: [
      { phase: "Network Administrator", duration: "0–3 Jahre" },
      { phase: "Senior Network Engineer", duration: "3–6 Jahre" },
      { phase: "Network Architect", duration: "6–9 Jahre" },
      { phase: "Head of Network Infrastructure", duration: "9+ Jahre" },
    ],
  },
  {
    slug: "cyber-security-analyst",
    title: "Cyber Security Analyst",
    icon: "shield",
    level: "Intermediate",
    duration: "6–12 Monate",
    salaryRange: "50–75k€",
    demand: "high",
    entrySalary: "56.000 €",
    openJobs: "6.200+",
    topCity: "Berlin, Frankfurt",
    skills: [
      "Threat Detection & Response",
      "SIEM-Tools",
      "Netzwerksicherheit",
      "Vulnerability-Management",
      "Sicherheitsrichtlinien & Compliance",
      "Incident-Response",
    ],
    recommendedCerts: [
      { code: "CompTIA Security+" },
      { code: "Azure Security Engineer Associate", link: { companySlug: "microsoft", certId: "az-500" } },
      { code: "Certified Ethical Hacker (CEH)" },
    ],
    roadmap: [
      { phase: "Cyber Security Analyst", duration: "0–3 Jahre" },
      { phase: "Security Engineer", duration: "3–6 Jahre" },
      { phase: "Security Architect", duration: "6–9 Jahre" },
      { phase: "CISO / Head of Security", duration: "9+ Jahre" },
    ],
  },
  {
    slug: "devops-engineer",
    title: "DevOps Engineer",
    icon: "devops",
    level: "Advanced",
    duration: "10–16 Monate",
    salaryRange: "55–75k€",
    demand: "high",
    entrySalary: "60.000 €",
    openJobs: "5.600+",
    topCity: "Berlin, München",
    skills: [
      "CI/CD-Pipelines",
      "Docker & Kubernetes",
      "Infrastructure as Code",
      "Cloud-Plattformen (Azure/AWS)",
      "Monitoring & Logging",
      "Automatisierungs-Scripting",
    ],
    recommendedCerts: [
      { code: "DevOps Engineer Expert", link: { companySlug: "microsoft", certId: "az-400" } },
      { code: "Certified Kubernetes Administrator (CKA)" },
      { code: "Docker Certified Associate" },
    ],
    roadmap: [
      { phase: "DevOps Engineer", duration: "0–3 Jahre" },
      { phase: "Senior DevOps Engineer", duration: "3–6 Jahre" },
      { phase: "Platform Engineer / SRE Lead", duration: "6–9 Jahre" },
      { phase: "Head of Platform Engineering", duration: "9+ Jahre" },
    ],
  },
  {
    slug: "database-engineer",
    title: "Database Engineer",
    icon: "database",
    level: "Intermediate",
    duration: "6–10 Monate",
    salaryRange: "55–75k€",
    demand: "medium",
    entrySalary: "58.000 €",
    openJobs: "3.400+",
    topCity: "Frankfurt, München",
    skills: [
      "SQL & Datenmodellierung",
      "Datenbank-Performance-Tuning",
      "Azure SQL / Cloud-Datenbanken",
      "Backup & Recovery",
      "Datensicherheit",
      "ETL-Prozesse",
    ],
    recommendedCerts: [
      { code: "Azure Data Fundamentals", link: { companySlug: "microsoft", certId: "dp-900" } },
      { code: "Oracle Database Certified Associate" },
      { code: "Azure Database Administrator Associate", link: { companySlug: "microsoft", certId: "dp-300" } },
    ],
    roadmap: [
      { phase: "Database Engineer", duration: "0–3 Jahre" },
      { phase: "Senior Database Engineer", duration: "3–6 Jahre" },
      { phase: "Data Architect", duration: "6–9 Jahre" },
      { phase: "Head of Data Engineering", duration: "9+ Jahre" },
    ],
  },
  {
    slug: "ai-engineer",
    title: "AI Engineer",
    icon: "ai",
    level: "Advanced",
    duration: "12–18 Monate",
    salaryRange: "60–90k€",
    demand: "high",
    entrySalary: "68.000 €",
    openJobs: "4.700+",
    topCity: "Berlin, München",
    skills: [
      "Machine-Learning-Grundlagen",
      "Python & Data Engineering",
      "Azure AI / Cognitive Services",
      "Modell-Deployment & MLOps",
      "Prompt Engineering",
      "Datenverarbeitung im großen Maßstab",
    ],
    recommendedCerts: [
      { code: "Azure AI Fundamentals", link: { companySlug: "microsoft", certId: "ai-900" } },
      { code: "Azure AI Engineer Associate", link: { companySlug: "microsoft", certId: "ai-102" } },
      { code: "Azure Data Scientist Associate", link: { companySlug: "microsoft", certId: "dp-100" } },
    ],
    roadmap: [
      { phase: "AI Engineer", duration: "0–3 Jahre" },
      { phase: "Senior AI / ML Engineer", duration: "3–6 Jahre" },
      { phase: "AI Solutions Architect", duration: "6–9 Jahre" },
      { phase: "Head of AI Engineering", duration: "9+ Jahre" },
    ],
  },
  {
    slug: "software-developer",
    title: "Software Developer",
    icon: "code",
    level: "Intermediate",
    duration: "6–12 Monate",
    salaryRange: "42–60k€",
    demand: "high",
    entrySalary: "48.000 €",
    openJobs: "10.500+",
    topCity: "Berlin, Hamburg",
    skills: [
      "Programmiersprachen (JS/Python/C#)",
      "Versionskontrolle (Git)",
      "APIs & Web-Services",
      "Datenbanken-Grundlagen",
      "Testing & Debugging",
      "Agile Entwicklungsmethoden",
    ],
    recommendedCerts: [
      { code: "Azure Developer Associate", link: { companySlug: "microsoft", certId: "az-204" } },
      { code: "AWS Certified Developer" },
      { code: "GitHub Foundations" },
    ],
    roadmap: [
      { phase: "Junior Software Developer", duration: "0–2 Jahre" },
      { phase: "Software Developer", duration: "2–5 Jahre" },
      { phase: "Senior Developer", duration: "5–8 Jahre" },
      { phase: "Tech Lead / Architect", duration: "8+ Jahre" },
    ],
  },
  {
    slug: "data-analyst",
    title: "Data Analyst",
    icon: "chart",
    level: "Beginner",
    duration: "4–6 Monate",
    salaryRange: "38–56k€",
    demand: "high",
    entrySalary: "44.000 €",
    openJobs: "5.900+",
    topCity: "München, Berlin",
    skills: [
      "Excel & Power BI",
      "SQL-Grundlagen",
      "Datenvisualisierung",
      "Statistik-Grundlagen",
      "Reporting & Dashboards",
      "Datenbereinigung",
    ],
    recommendedCerts: [
      { code: "Power BI Data Analyst Associate", link: { companySlug: "microsoft", certId: "pl-300" } },
      { code: "Azure Data Fundamentals", link: { companySlug: "microsoft", certId: "dp-900" } },
      { code: "Google Data Analytics Certificate" },
    ],
    roadmap: [
      { phase: "Data Analyst", duration: "0–2 Jahre" },
      { phase: "Senior Data Analyst", duration: "2–5 Jahre" },
      { phase: "Data Scientist / BI Lead", duration: "5–8 Jahre" },
      { phase: "Head of Analytics", duration: "8+ Jahre" },
    ],
  },
  {
    slug: "it-project-manager",
    title: "Project Manager (IT)",
    icon: "kanban",
    level: "Intermediate",
    duration: "6–9 Monate",
    salaryRange: "55–70k€",
    demand: "medium",
    entrySalary: "58.000 €",
    openJobs: "3.100+",
    topCity: "Frankfurt, München",
    skills: [
      "Agile & Scrum",
      "Projektplanung & Budgetierung",
      "Stakeholder-Management",
      "Risikomanagement",
      "IT-Grundlagen",
      "Teamführung",
    ],
    recommendedCerts: [
      { code: "ITIL 4 Foundation" },
      { code: "Project Management Professional (PMP)" },
      { code: "Professional Scrum Master (PSM)" },
    ],
    roadmap: [
      { phase: "Junior Project Manager", duration: "0–2 Jahre" },
      { phase: "IT Project Manager", duration: "2–5 Jahre" },
      { phase: "Senior Program Manager", duration: "5–8 Jahre" },
      { phase: "Head of IT-Projekte", duration: "8+ Jahre" },
    ],
  },
];

export function getCareerPath(slug: string): CareerPath | undefined {
  return careerPaths.find((p) => p.slug === slug);
}
